### ISSUE TITLE
Reference ansible inventory instead of defining them inside the playbook 

### ISSUE THREAD

**Issue by rottenit** [bellackn/ansible-collection-homelab#18]
This totally could be my level of experience with ansible but would it be possible to define the host variables inside the default inventory.yml instead of inside the playbook?

Thanks!

**Comment by bellackn** [comment]
yes, this is totally possible. all you need to make sure is that the host you're targeting has the necessary variables in scope. you can either define those variables in the inventory (as you're asking), as host_vars, group_vars, facts, on the command line, ... whatever you prefer.

i suggest you have a look at the ansible docs. especially [this](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#where-to-set-variables) and [this](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#tips-on-where-to-set-variables) might be helpful for you.

for example, imagine you'd use host_vars, then your project could look something like this:

```
# ./host_vars/proxmox/bellackn.homelab.proxmox_lxc.yml
---
proxmox_lxc_api_host: something
proxmox_lxc_containers_present:
  - ...
[...]
# all the variables go here
```

and then the playbook itself stays very lean:
```
- name: Set up LXCs
  hosts: proxmox
  gather_facts: no
  roles:
    - bellackn.homelab.proxmox_lxc
```

this works because ansible automatically maps any variable inside `host_vars/<the host>` to plays that target `<the host>`.

**Comment by rottenit** [comment]
Thanks! I am still struggling, for example in my provisioning playbook if I target the test-1 machine with "hosts: test-1" it tries to run the "geerlingguy.pip : Get python3 version installed" task on test-1 which hasn't been created yet. 

What should be the target of the playbook?

Thanks!

**Comment by bellackn** [comment]
the target of the playbook which runs the `bellackn.homelab.proxmox_lxc` role can only be a host which runs proxmox.
if you have created some containers and want to target these, you need to add them to your inventory after you created them.

**Comment by bellackn** [comment]
i will close this issue now since this is not about the collection/role, but general ansible questions. if you want to continue discussing this, you can reach me via matrix chat: https://matrix.to/#/@bellackn:matrix.org

**Comment by rottenit** [comment]
Got it, thanks for the help!
